# Use root/example as user/password credentials
version: '3.1'

services:
  gradle:
    image: gradle:7.6.1-jdk17
#    image: gradle:7.6.1-jdk17-alpine
    container_name: ootd-be
#    restart: always
    volumes:
      - ./data:/home/gradle/.gradle
      - ../../ootd-be:/home/gradle/project
      - ~/DATA:/home/gradle/DATA
    working_dir: /home/gradle/project
#    entrypoint: ["/bin/sh", "-c", "gradle :api:build -x test && gradle :api:bootRun --args='--spring.profiles.active=docker'"]
    entrypoint: gradle :api:bootRun --args='--spring.profiles.active=docker'
    user: gradle
    ports:
      - 60002:8080
    networks:
      - default
      - ootd_net

networks:
  ootd_net:
    external: true
