# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
#    stable 기준
    image: nginx:1.22-alpine
    container_name: ootd-proxy
#    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./data/log:/var/log/nginx
      - ../node/data/build:/usr/share/nginx/html
      - ~/DATA:/DATA
    networks:
      - ootd_net
    ports:
      - 80:80

networks:
  ootd_net:
    external: true
