# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.11.2-jammy
    container_name: ootd-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ootd!@#123
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 60001:3306
    networks:
      - ootd_net

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

networks:
  ootd_net:
    external: true
